# Generated by Django 3.0.8 on 2020-08-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Fullname Placeholder', max_length=100),
            preserve_default=False,
        ),
    ]
